# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' src_fn
#'
#' A test C++ function
#' @srrstats {G2.3} in src directory
#' @noRd
test <- function() {
    .Call(`_jsonschema_test`)
}

