# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_json_validate <- function(schema_name, json_name) {
    invisible(.Call(`_jsonschema_rcpp_json_validate`, schema_name, json_name))
}

